### ISSUE TITLE
remove vendor and shift to use go.mod

### ISSUE THREAD

**Issue by yabetsu1993** [qvl/promplot#23]
currently as golang is 1.9 atm this is good to update it to go mod and add envrc to directly identified the golang path

**Comment by jorinvo** [comment]
Hi there! Sounds good to me! Feel free to contribute changes. Personally I am not using the project right now, but if you like to continue working on it, I am happy to accept the changes :)

**Comment by yabetsu1993** [comment]
Sure i want to work out with it thanks!

**Comment by yabetsu1993** [comment]
i updated it but encounter some issues i removed vendor folder and use mod.go sorry for the late update

**Comment by yabetsu1993** [comment]
related pull request this will resolve this issue
https://github.com/qvl/promplot/pull/26
